config/routes.rb
Rails.application.routes.draw do

  root 'top#index'

  get 'playground' => 'top#playground'

  get 'join' => 'users#new'
  post 'join' => 'users#create'

  get 'signin' => 'session#new'
  post 'signin' => 'session#create'
  get 'signout' => 'session#destroy'

  resource :items do
    collection do
    end
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :items

  validates :username, :emailid, :password_digest, presence: { message: 'can not be empty' }
  validates :username, :emailid, uniqueness: { message: 'already exists' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :require_login

  def new
    @item = current_user.items.new
  end

  def show
    @items = current_user.items
  end

  def create
    @item = current_user.items.new(item_params)

    if @item.save
      redirect_to '/items'
    else
      render 'new'
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :image, :race, :cloth, :gender, :metalware_info, :inchant_info, :description)
  end

  def require_login
    redirect_to :root if current_user.nil?
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by_emailid(params[:emailid])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
      flash.now[:danger] = 'invalid email/password'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    puts 'Hello world!'
  end

  def playground
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :emailid, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/new.html.erb
<h1>Add Item!</h1>

<%= form_for @item do |f| %>
  <% if @item.errors.any? %>
    <div id='error_explanation'>
      <h2>
        <%= pluralize(@item.errors.count, 'error') %> prohibited
        this item from being saved:
      </h2>
      <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row field_text">
    Name: <%= f.text_field :name %>
  </div>
  <div class="row field_text">
    Image: <%= f.text_field :image %>
  </div>
  <div class="row field_text">
    Race: <%= f.password_field :race %>
  </div>
  <div class="row field_text">
    Cloth: <%= f.password_field :cloth %>
  </div>
  <div class="row field_text">
    Gender: <%= f.password_field :gender %>
  </div>
  <div class="row field_text">
    Metalware: <%= f.password_field :metalware_info %>
  </div>
  <div class="row field_text">
    Inchant: <%= f.password_field :inchant_info %>
  </div>
  <div class="row field_text">
    Description: <%= f.password_field :description %>
  </div>

  <span class="btn btn-blue">
    <%= f.submit 'Submit' %>
  </span>
<% end %>

app/views/items/show.html.erb
<% @items.each do |item| %>
  <tr>
    <td><%= item.id %></td>
    <td><%= item.name %></td>
  </tr>
<% end %>

<%= link_to 'Add Item', new_items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="no-js">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <!-- Side Menu -->
    <%= render 'layouts/menu/side' %>
    <!--/ Side Menu -->

    <div id='main'>
      <!-- Website Menu -->
      <%= render 'layouts/menu/top' %>
      <!--/ Website Menu -->


      <div class="container container-wide">
        <!-- content -->
        <div class="content " role="main">
          <%= yield %>
        </div>
        <!--/ content -->
      </div>
      <!--/ container -->
    </div>
  </body>
</html>

app/views/layouts/area/_pricing_box.html.erb
<div class="pricing_box">
    <ul class="clearfix">
        <li class="price_col price_col_blue ">
            <!--pricing item-->
            <div class="price_item boxed">
                <div class="price_col_head">
                    <span class="badge"></span>
                    <span class="price"><em>$</em>199<sup>90</sup></span>
                </div>
                <div class="price_col_body clearfix">
                    <div class="price_body_inner">
                        <div class="price_body_top">
                            <span>Full Circle</span>
                            <strong>Basic</strong>
                            <div class="line"></div>
                        </div>
                        <ul>
                            <li>Unlimited Traffic</li>
                            <li>20 gb in Cloud</li>
                            <li>0.5 gbit/sec</li>
                        </ul>
                    </div>
                </div>
                <div class="price_col_foot">
                    <div class="sign_up"><a href="#" class="btn btn-blue btn-small"><span>Buy Now</span></a></div>
                </div>
            </div>
            <!--/ pricing-item -->
        </li>

        <li class="price_col price_col_red col_active">
            <div class="price_item boxed">
                <div class="price_col_head">
                    <span class="badge"></span>
                    <span class="price"><em>$</em>299<sup>90</sup></span>
                </div>
                <div class="price_col_body clearfix">
                    <div class="price_body_inner">
                        <div class="price_body_top">
                            <span>Full Circle</span>
                            <strong>Premium</strong>
                            <div class="line"></div>
                        </div>
                        <ul>
                            <li>Unlimited Traffic</li>
                            <li>50 gb in Cloud</li>
                            <li>1 gbit/sec</li>
                        </ul>
                    </div>
                </div>
                <div class="price_col_foot">
                    <div class="sign_up"><a href="#" class="btn btn-red"><span>Buy Now</span></a></div>
                </div>
            </div>
        </li>

        <li class="price_col price_col_green ">
            <div class="price_item boxed">
                <div class="price_col_head">
                    <span class="badge"></span>
                    <span class="price"><em>$</em>399<sup>90</sup></span>
                </div>
                <div class="price_col_body clearfix">
                    <div class="price_body_inner">
                        <div class="price_body_top">
                            <span>Full Circle</span>
                            <strong>Ultimate</strong>
                            <div class="line"></div>
                        </div>
                        <ul>
                            <li>Unlimited Traffic</li>
                            <li>80 gb in Cloud</li>
                            <li>2 gbit/sec</li>
                        </ul>
                    </div>
                </div>
                <div class="price_col_foot">
                    <div class="sign_up"><a href="#" class="btn btn-green btn-small"><span>Buy Now</span></a></div>
                </div>
            </div>
        </li>
    </ul>
</div>

app/views/layouts/area/_tab.html.erb
<div class="tabs_framed styled">
    <ul class="tabs clearfix">
        <li class="active"><a href="#about" data-toggle="tab">About</a></li>
        <li><a href="#history" data-toggle="tab">History</a></li>
        <li><a href="#past" data-toggle="tab">Past</a></li>
    </ul>

    <div class="tab-content boxed clearfix">
        <div class="tab-pane fade in active" id="about">
            <div class="inner clearfix">
                <div class="tab_image pull-left"><img src="images/temp/tabimage8.png" alt=""></div>
                <h2><a href="#">Michael Ormond</a></h2>
                <!-- Rating Stars -->
                <div class="rating">
                    <span class="star on"><input type="hidden" value="1"></span><!--
                                    --><span class="star on"><input type="hidden" value="2"></span><!--
                                    --><span class="star on"><input type="hidden" value="3"></span><!--
                                    --><span class="star off"><input type="hidden" value="4"></span><!--
                                    --><span class="star off"><input type="hidden" value="5"></span>
                </div>
                <!--/ Rating Stars -->
                <div class="tab-text"><p>He made his film debut with a minor part in Back to The Future Part II and then he became very popular.</p></div>
                <div class="buttons">
                    <a href="#" class="btn"><span>Normal</span></a>
                    <a href="#" class="btn hover"><span>Hover</span></a>
                    <a href="#" class="btn active"><span>Pressed</span></a>
                </div>
                <div class="buttons">
                    <a href="#" class="btn btn-left"><span>&nbsp;&nbsp;Left&nbsp;</span></a>
                    <a href="#" class="btn btn-green"><span>Change</span></a>
                    <a href="#" class="btn btn-right"><span>Right&nbsp;</span></a>
                </div>
            </div>
            <div class="bottom clearfix">
                <div class="tagcloud pull-right">
                    <a href="#" class="tag-link-1" title="2 topics"><span>Web Design</span></a>
                    <a href="#" class="tag-link-2" title="3 topics"><span>Illustration</span></a>
                    <a href="#" class="tag-link-3" title="5 topics"><span>Fashion Style</span></a>
                    <a href="#" class="tag-link-4" title="8 topics"><span>Typography</span></a>
                    <a href="#" class="tag-link-5" title="9 topics"><span>Interface</span></a>
                    <a href="#" class="tag-link-6" title="3 topics"><span>High resolution</span></a>
                </div>
                <h3>Tags</h3>
                <p>He made his film debut with a minor part in Back to The Future Part II</p>
            </div>
        </div>
        <div class="tab-pane fade" id="history">
            <div class="inner clearfix">
                <div class="tab_image pull-right"><img src="images/temp/tabimage9.png" alt=""></div>
                <h2><a href="#">Elijah Wood</a></h2>
                <!-- Rating Stars -->
                <div class="rating">
                    <span class="star on"><input type="hidden" value="1"></span><!--
                                    --><span class="star on"><input type="hidden" value="2"></span><!--
                                    --><span class="star on"><input type="hidden" value="3"></span><!--
                                    --><span class="star on"><input type="hidden" value="4"></span><!--
                                    --><span class="star off"><input type="hidden" value="5"></span>
                </div>
                <!--/ Rating Stars -->
                <div class="tab-text"><p>He made his film debut with a minor part in Back to The Future Part II and then he became very popular.</p></div>
                <div class="buttons">
                    <a href="#" class="btn"><span>Normal</span></a>
                    <a href="#" class="btn hover"><span>Hover</span></a>
                    <a href="#" class="btn active"><span>Pressed</span></a>
                </div>
                <div class="buttons">
                    <a href="#" class="btn btn-left"><span>&nbsp;&nbsp;Left&nbsp;</span></a>
                    <a href="#" class="btn btn-green"><span>Change</span></a>
                    <a href="#" class="btn btn-right"><span>Right&nbsp;</span></a>
                </div>
            </div>
            <div class="bottom clearfix">
                <div class="tagcloud pull-left">
                    <a href="#" class="tag-link-1" title="2 topics"><span>Web Design</span></a>
                    <a href="#" class="tag-link-2" title="3 topics"><span>Illustration</span></a>
                    <a href="#" class="tag-link-3" title="5 topics"><span>Fashion Style</span></a>
                    <a href="#" class="tag-link-4" title="8 topics"><span>Typography</span></a>
                    <a href="#" class="tag-link-5" title="9 topics"><span>Interface</span></a>
                    <a href="#" class="tag-link-6" title="3 topics"><span>High resolution</span></a>
                </div>
                <h3>Tags</h3>
                <p>He made his film debut with a minor part in Back to The Future Part II</p>
            </div>
        </div>
        <div class="tab-pane fade" id="past">
            <div class="inner clearfix">
                <div class="tab_image pull-left"><img src="images/temp/tabimage10.png" alt=""></div>
                <h2><a href="#">John Carpenter</a></h2>
                <!-- Rating Stars -->
                <div class="rating">
                    <span class="star on"><input type="hidden" value="1"></span><!--
                                    --><span class="star on"><input type="hidden" value="2"></span><!--
                                    --><span class="star on"><input type="hidden" value="3"></span><!--
                                    --><span class="star on"><input type="hidden" value="4"></span><!--
                                    --><span class="star off"><input type="hidden" value="5"></span>
                </div>
                <!--/ Rating Stars -->
                <div class="tab-text"><p>He made his film debut with a minor part in Back to The Future Part II and then he became very popular.</p></div>
                <div class="buttons">
                    <a href="#" class="btn"><span>Normal</span></a>
                    <a href="#" class="btn hover"><span>Hover</span></a>
                    <a href="#" class="btn active"><span>Pressed</span></a>
                </div>
                <div class="buttons">
                    <a href="#" class="btn btn-left"><span>&nbsp;&nbsp;Left&nbsp;</span></a>
                    <a href="#" class="btn btn-green"><span>Change</span></a>
                    <a href="#" class="btn btn-right"><span>Right&nbsp;</span></a>
                </div>
            </div>
            <div class="bottom clearfix">
                <div class="tagcloud pull-left">
                    <a href="#" class="tag-link-1" title="2 topics"><span>Web Design</span></a>
                    <a href="#" class="tag-link-2" title="3 topics"><span>Illustration</span></a>
                    <a href="#" class="tag-link-3" title="5 topics"><span>Fashion Style</span></a>
                    <a href="#" class="tag-link-4" title="8 topics"><span>Typography</span></a>
                    <a href="#" class="tag-link-5" title="9 topics"><span>Interface</span></a>
                    <a href="#" class="tag-link-6" title="3 topics"><span>High resolution</span></a>
                </div>
                <h3>Tags</h3>
                <p>He made his film debut with a minor part in Back to The Future Part II</p>
            </div>
        </div>
    </div>
</div>

app/views/layouts/menu/_joinup.html.erb
<!-- join/signup menu shown unless signed in -->
<li class="pull-right"><a href="signin"><span>Sign in</span></a></li>
<li class="pull-right"><a href="join"><span>Join</span></a></li>
<!--/ join/signup menu -->

app/views/layouts/menu/_profile.html.erb
<!-- profile menu shown if signed in -->
<li class="pull-right"><a href="signout"><i class="icon-menu icon-menu6"></i><span>Sign out</span></a></li>
<li class="pull-right"><a href="#"><i class="icon-menu icon-menu5"></i><span>My Profile</span></a>
    <ul>
        <li><a href="/items">Items</a></li>
        <li><a href="#">find friends</a></li>
        <li><a href="#">Log out</a></li>
    </ul>
</li>
<!-- /profile menu -->

app/views/layouts/menu/_side.html.erb
<div id="sideMenu" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <a href="#">About</a>
  <a href="#">Services</a>
  <a href="#">Clients</a>
  <a href="#">Contact</a>
</div>

app/views/layouts/menu/_top.html.erb
<div id="topmenu">
    <ul class="dropdown clearfix boxed">
        <li class="menu-level-0"><a href="#"><i class="icon-menu"></i><span>check in</span><sup class="note">3</sup></a></li>
        <li class="menu-level-0"><a href="#"><i class="icon-menu icon-menu2"></i><span>events</span></a> </li>
        <li class="menu-level-0"><a href="#"><i class="icon-menu icon-menu3"></i><span>account</span></a>
            <ul class="submenu-1">
                <li class="menu-level-1"><a href="#">Web design</a></li>
                <li class="menu-level-1"><a href="#">User interface</a></li>
                <li class="menu-level-1"><a href="#">Social media</a>
                    <ul class="submenu-2">
                        <li class="menu-level-2"><a href="#">Gallery images</a></li>
                        <li class="menu-level-2"><a href="#">Fine Slider</a></li>
                        <li class="menu-level-2"><a href="#">Video in header</a></li>
                        <li class="menu-level-2"><a href="#">Video Slider</a>
                            <ul class="submenu-3">
                                <li class="menu-level-3"><a href="#">Item 1</a></li>
                                <li class="menu-level-3"><a href="#">Item 2</a></li>
                                <li class="menu-level-3"><a href="#">Item 3</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>
        <li class="menu-level-0"><a href="#"><i class="icon-menu icon-menu4"></i><span>settings</span></a></li>

        <% if current_user %>
          <%= render 'layouts/menu/profile' %>
        <% else %>
          <%= render 'layouts/menu/joinup' %>
        <% end %>
    </ul>
</div>

app/views/layouts/menu/_user.html.erb
<div class="user-menu">
    <ul class="dropdown clearfix boxed">
        <li class="hover"><a href="#"><i class="icon-menu icon-menu5"></i><span>My Profile</span></a>
            <ul>
                <li><a href="#">Invite friends</a></li>
                <li><a href="#">find friends</a></li>
                <li><a href="#">Log out</a></li>
            </ul>
        </li>
        <li><a href="#"><i class="icon-menu icon-menu6"></i><span>Edit Profile</span></a></li>
    </ul>
</div>

app/views/layouts/widget/_audio.html.erb
<div class="widget-container widget-audio boxed">
    <div class="inner">
        <div id="jquery_jplayer_1" class="jp-jplayer"></div>
        <div id="jp_container_1" class="jp-audio">
            <div class="inner">
                <div class="jp-gui jp-interface">
                    <div class="jp-controls-wrap">
                        <div class="song_title"></div>
                        <div class="jp-current-time"></div>
                        <div class="jp-duration"></div>
                        <div class="jp-progress">
                            <div class="jp-seek-bar">
                                <div class="jp-play-bar"></div>
                            </div>
                        </div>
                        <ul class="jp-controls clearfix">
                            <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
                            <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
                            <li><a href="javascript:;" class="jp-previous disabled" tabindex="1">previous</a></li>
                            <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
                            <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
                            <li><a href="javascript:;" class="jp-next" tabindex="1">next</a></li>
                            <li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
                            <li><a href="javascript:;" class="jp-repeat" tabindex="1" title="repeat">repeat</a></li>
                            <li><a href="javascript:;" class="jp-repeat-off" tabindex="1" title="repeat off">repeat off</a></li>
                            <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
                            <li><a href="javascript:;" class="jp-shuffle" tabindex="1" title="shuffle">shuffle</a></li>
                            <li><a href="javascript:;" class="jp-shuffle-off" tabindex="1" title="shuffle off">shuffle off</a></li>
                            <li><a href="javascript:;" class="jp-playlist-toggle" tabindex="1" title="Toggle PlayList">Toggle PlayList</a></li>
                        </ul>
                        <div class="jp-volume-bar">
                            <div class="jp-volume-bar-value"></div>
                        </div>
                    </div>
                </div>
                <div class="jp-playlist">
                    <ul class="jp-playlist-inner">
                        <li></li>
                    </ul>
                </div>
                <div class="jp-no-solution">
                    <span>Update Required</span>
                    <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/widget/_avatar.html.erb
<div class="widget-container widget_avatar boxed">
    <div class="avatar-image"><img src="images/temp/avatar-image.jpg" alt="" /></div>
    <div class="inner clearfix">
        <div class="avatar"><img src="images/temp/avatar.png" alt="" /></div>
        <h5>John Raymons</h5>
        <span class="subtitle">Your talent amazes! This is awesome. Excited to see the final product.</span>
    </div>
    <div class="post-meta-links">
        <ul class="clearfix">
            <li class="post-view"><a href="#"><span><i class="icon-post"></i>172</span></a></li>
            <li class="post-comm"><a href="#"><span><i class="icon-post"></i>34</span></a></li>
            <li class="post-like"><a href="#"><span><i class="icon-post"></i>210</span></a></li>
        </ul>
    </div>
</div>

app/views/layouts/widget/_calendar.html.erb
<div class="widget-container widget_calendar boxed styled">
    <div class="inner">
        <input type="text" name="date_departure" class="inputField" value="" id="date_departure">
        <script>
            // <![CDATA[
            jQuery(document).ready(function($) {
                var daysRange = 5;

                function assignCalendar(id){
                    $('<div class="calendar" />')
                            .insertAfter( $(id) )
                            .multiDatesPicker({
                                dateFormat: 'yy-mm-dd',
                                minDate: new Date(),
                                maxDate: '+1y',
                                altField: id,
                                firstDay: 1,
                                showOtherMonths: true
                            }).prev().hide();
                }

                assignCalendar('#date_departure');
            });
            // ]]>
        </script>
    </div>
</div>

app/views/layouts/widget/_gallery.html.erb
<div class="widget-container widget_gallery boxed">
    <div class="inner">
        <div id="myCarousel" class="carousel slide" data-interval="20000">
            <!-- Carousel items -->
            <div class="carousel-inner">
                <div class="active item"><img src="images/temp/post_img6.jpg" alt="" /><div class="carousel-desc"><span>Wild Deer</span></div></div>
                <div class="item"><img src="images/temp/post_img1.jpg" alt="" /><div class="carousel-desc"><span>Change your fate</span></div></div>
                <div class="item"><img src="images/temp/post_img3.jpg" alt="" /><div class="carousel-desc"><span>Unstoppable hero</span></div></div>
                <div class="item"><img src="images/temp/post_img2.jpg" alt="" /><div class="carousel-desc"><span>Change your fate</span></div></div>
                <div class="item"><img src="images/temp/post_img4.jpg" alt="" /><div class="carousel-desc"><span>Unstoppable hero</span></div></div>
            </div>
            <!-- Carousel indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
                <li data-target="#myCarousel" data-slide-to="4"></li>
            </ol>
            <!-- Carousel nav -->
            <a class="carousel-control left" href="#myCarousel" data-slide="prev"></a>
            <a class="carousel-control right" href="#myCarousel" data-slide="next"></a>
        </div>
    </div>
</div>

app/views/layouts/widget/_search.html.erb
<div class="widget-container widget_search styled boxed line-left">
    <div class="inner">
        <form method="get" id="searchform2" action="#">
            <div class="clearfix">
                <span class="btn"><input type="submit" value="Search" /></span>
                <div class="field_text"><input name="search" value="" type="text" placeholder="Type word here" /></div>
            </div>
        </form>
    </div>
</div>

app/views/layouts/widget/_social.html.erb
<div class="widget-container widget-social boxed">
    <ul>
        <li><a href="#" class="social-facebook"><span>Facebook</span></a></li>
        <li><a href="#" class="social-pinterest"><span>Pinterest</span></a></li>
        <li><a href="#" class="social-twitter"><span>Twitter</span></a></li>
    </ul>
</div>

app/views/layouts/widget/_stats.html.erb
<div class="tabs_framed styled widget-stats">
    <ul class="tabs clearfix">
        <li class="active"><a href="#diagram" data-toggle="tab">Diagram Stats</a></li>
        <li><a href="#month" data-toggle="tab">Month Report</a></li>
    </ul>

    <div class="tab-content boxed clearfix">
        <div class="tab-pane fade in active" id="diagram">
            <h6>Data Transfer</h6>
            <div id="donutchart" class="donutchart"></div>
            <ul class="stats-data clearfix">
                <li><a href="#"><span>audio</span><strong>55%</strong></a></li>
                <li class="red"><a href="#"><span>video</span><strong>23%</strong></a></li>
                <li class="yellow"><a href="#"><span>photo</span><strong>17%</strong></a></li>
            </ul>
            <ul class="stats-links clearfix">
                <li><a href="#"><i class="stats-icon stats-icon1"></i><br /><span>upload files</span></a></li>
                <li><a href="#"><i class="stats-icon stats-icon2"></i><br /><span>share link</span></a></li>
                <li><a href="#"><i class="stats-icon stats-icon3"></i><br /><span>back up</span></a></li>
            </ul>
        </div>
        <div class="tab-pane fade" id="month">
            <h6>Data chart</h6>
            <div id="columnchart" class="columnchart"></div>
            <ul class="stats-data clearfix">
                <li><a href="#"><span>audio</span><strong>50%</strong></a></li>
                <li class="red"><a href="#"><span>video</span><strong>26%</strong></a></li>
                <li class="yellow"><a href="#"><span>photo</span><strong>18%</strong></a></li>
            </ul>
            <ul class="stats-links clearfix">
                <li><a href="#"><i class="stats-icon stats-icon1"></i><br /><span>upload files</span></a></li>
                <li><a href="#"><i class="stats-icon stats-icon2"></i><br /><span>share link</span></a></li>
                <li><a href="#"><i class="stats-icon stats-icon3"></i><br /><span>back up</span></a></li>
            </ul>
        </div>
    </div>
</div>

app/views/layouts/widget/_trade.html.erb
<div class="widget-container widget-trade boxed">
    <div class="widget-title">
        <span class="trade-rate trade-rate-up">634. 39</span>
        <span class="trade-rate-change">+2.18 (3.71%)</span>
    </div>
    <div class="inner">
        <div class="trade-time">Today 2:25 pm</div>
        <h4 class="trade-location"><a href="#">Salt Lake City, Utah</a></h4>
        <ul class="trade-shares clearfix">
            <li class="traded"><a href="#"><strong>13.5 M</strong><span>Shares Traded</span></a></li>
            <li class="capitalization"><a href="#"><strong>28.44 B</strong><span>Market Cap</span></a></li>
        </ul>
        <div class="trade-bottom trade-graph">
            <h6 class="trade-bottom-title">AAPL</h6>
            <div class="trade-bottom-content"><img src="images/trade-graph.png" alt="" /></div>
        </div>
        <div class="trade-bottom trade-yearly-change">
            <h6 class="trade-bottom-title">Yearly Change</h6>
            <div class="trade-bottom-content"><span>+127. 01</span></div>
        </div>
        <div class="clear"></div>
    </div>
</div>

app/views/layouts/widget/_weather.html.erb
<div class="widget-container widget-weather boxed clearfix">
    <div class="air-temp"><strong>26&deg;</strong></div>
    <div class="water-temp"><strong>14&deg;</strong></div>
    <div class="wind-speed"><strong>13</strong></div>
</div>

app/views/session/new.html.erb
<h1>Sign in</h1>

<%= form_tag 'signin' do %>
  <% if flash[:danger] %>
    <div class="notice"><%= flash[:danger] %></div>
  <% end %>

  <div class="row field_text">
    Email: <%= text_field_tag :emailid %>
  </div>
  <div class="row field_text">
    Password: <%= password_field_tag :password %>
  </div>

  <span class="btn btn-blue">
    <%= submit_tag 'Submit' %>
  </span>
<% end %>